### ISSUE TITLE
Restart-emacs not listed on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [iqbalansari/restart-emacs#1]
Hi Iqbal, thanks for sharing this package! Perfectly, what I need! 

Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by iqbalansari** [comment]
Hi ReneFroger,

I added this package to MELPA today, forgot to update README though. Let me fix it. Thanks for the heads up

**Comment by iqbalansari** [comment]
I have updated the README to include installation instructions. Thanks!
