### ISSUE TITLE
will restart-emacs stop and start am emacs --deamon?

### ISSUE THREAD

**Issue by zeltak** [iqbalansari/restart-emacs#4]
Hi

very neat!

will restart-emacs stop and start am emacs --daemon or is it aimed only for standalone emacs?

i use emacs --deamon and start emacs with emacsclient so i wonder if this would work here

best

Z

**Comment by iqbalansari** [comment]
Hi,

It should be able to restart daemon Emacs, with the caveat that terminal emacsclient instances cannot be restored. There an issue open for this (#3), unfortunately I didn't enough time to work on this, hoping to work on this during the weekend

Thanks

**Comment by iqbalansari** [comment]
Hi, I am closing this in favor of #3
